### ISSUE TITLE
Vodný kanál na Českej má vzdušné bubliny

### ISSUE THREAD

**Issue by JohnDumpling** [singularis-mzf/cesky-hvozd#2]
Vodný kanál uprostred ulice má na oboch okrajoch vzduchové bubliny namiesto vody. Pravdepodobne kvôli použitiu grass slopes ich nie je možné vyplniť vodou.

**Comment by singularis-mzf** [comment]
Děkuji za hlášení. S vyřešením tohoto problému do budoucna počítám.

**Comment by singularis-mzf** [comment]
Opraveno a oprava nasazena.
