### ISSUE TITLE
Nemožnosť používať nabíjacie stanice v Dielni

### ISSUE THREAD

**Issue by JohnDumpling** [singularis-mzf/cesky-hvozd#3]
Na obrázku je vidno chybové hlásenie, ktoré nedovoľuje hráčovi používať verejné nabíjacie stanice v Dielni v zabezpečenej oblasti:
![obrázok](https://user-images.githubusercontent.com/89086803/199030708-a49b6692-3ae9-4311-b160-562a59544d2b.png)

**Comment by singularis-mzf** [comment]
Důvodem je, že jsem už začal/a zavádět omezení nových postav. Cílem je, aby si nové postavy mohly svět jen prohlížet (a případně si dopisovat s ostatními), ale nemohly v něm těžit, stavět, obchodovat či zanechávat po sobě nějaké stopy, dokud neabsolvují přijímací pohovor (ale chystám jako alternativu k pohovoru dotazník). Moje původní představa byla, že jim nedám právo interact, jenže to by jim zabránilo také např. nastupovat do vlaků, otevírat si dveře nebo si sednout na židli, což jsou věci, které i novým postavám dovolit určitě chci.

Hlavní chybou tedy je, že tento můj záměr není srozumitelně sdělovaný novým hráčům/kám. Pokusím se na tom zapracovat.

**Comment by singularis-mzf** [comment]
Napsal/a jsem vám (jako Administrace) zprávu herní poštou. (Doufám, že jsem se trefil/a.)

**Comment by JohnDumpling** [comment]
Ďakujem za objasnenie. A áno, trafili ste sa, správa mi bola doručená.
